FROM node:alpine as build
ARG REACT_APP_API_URL
WORKDIR /app
COPY ./package.json ./
RUN npm i
COPY ./ ./
RUN REACT_APP_API_URL=${REACT_APP_API_URL} npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]